name: gradio_graph

on:
  push:
    branches:
      - "main"

env:
  CI: true
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
      name: build
      runs-on: ubuntu-22.04
      steps:
      - uses: actions/checkout@v3
        with:
          # Relative path under $GITHUB_WORKSPACE to place the repository
          path: ''

          # Whether to execute `git clean -ffdx && git reset --hard HEAD` before fetching
          # Default: true
          clean: ''

          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Default: 1
          fetch-depth: 1
          
          # Add repository path as safe.directory for Git global config by running `git
          # config --global --add safe.directory <path>`
          # Default: true
          set-safe-directory: ''

          # The base URL for the GitHub instance that you are trying to clone from, will use
          # environment defaults to fetch from the same instance that the workflow is
          # running from unless specified. Example URLs are https://github.com or
          # https://my-ghes-server.example.com
          # github-server-url: ''
      - name: Install dependencies
        run: >
          sudo apt-get update && 
          sudo apt-get install -y software-properties-common &&
          sudo add-apt-repository ppa:deadsnakes/ppa && 
          sudo apt-get install -y git python3.9 python3.9-distutils nodejs curl python-is-python3 && 
          sudo npm install -g pnpm && 
          sudo curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && 
          sudo python3.9 get-pip.py
      - name: Build gradio
        run: >
          bash scripts/install_gradio.sh && 
          bash scripts/build_frontend.sh
